### ISSUE TITLE
Home page vaccination diagram

### ISSUE THREAD

**Issue by sotiriosalpha** [mousaviamirhossein/Covid-Media-Web#3]
As in #1 ,  I would suggest we wrap all cards inside the limits of the menu: 1140px for large screen and this would be the "container" max width

![image](https://user-images.githubusercontent.com/39827015/112761308-5cbb1c00-9003-11eb-9474-65675fdf2bd9.png)

**Comment by mousaviamirhossein** [comment]
If I understand correctly, fixed!
